--- #YAML:1.0
name:                FormValidator-Simple-Plugin-Math
version:             0.02
abstract:            Math evaluation for FormValidator::Simple
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Yusuke Sugiyama <ally@blinkingstar.net>
