---
abstract: 'Math evaluation for FormValidator::Simple'
author:
  - 'Yusuke Sugiyama, C<< <ally at blinkingstar.net> >>'
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: FormValidator-Simple-Plugin-Math
no_index:
  directory:
    - inc
    - t
requires:
  FormValidator::Simple::Constants: 0
  Math::Expression: 0
  Test::More: 0
version: 0.03
